---

hosts:
        - host: srv.nan-elmoth.ru
          users:
                - user: web1
                  authorized:
                        - person: schors
                - user: web2
                  authorized:
                        - person: schors
                - user: web3
                  authorized:
                        - person: schors
                - user: sms
                  authorized:
                        - person: schors
                - user: door
                  authorized:
                        - person: schors
                        - person: adnull
                        - person: andrey
        - host: tools.bz8.ru
          users:
                - user: door
                  authorized:
                        - person: adnull
                        - person: schors
        - host: nagios.bz8.ru
          users:
                - user: door
                  authorized:
                        - person: adnull
                        - person: schors
                        - person: andrey

